In [1]:
# Set the seed value for the notebook so the results are reproducible
from numpy.random import seed
seed(1)

In [2]:
# Dependencies
import numpy as np
import pandas as pd

In [3]:
import tensorflow
tensorflow.keras.__version__

'2.2.4-tf'

In [4]:
HappinessCSV = pd.read_csv('YR2015_2019FinalML3.csv')
HappinessCSV

,Country,Freedom2015,Freedom2016,Freedom2017,Freedom2018,Freedom2019,GDP2015,GDP2016,GDP2017,GDP2018,...,Social_Support2015,Social_Support2016,Social_Support2017,Social_Support2018,Social_Support2019,Happiness2015,Happiness2016,Happiness2017,Happiness2018,Happiness2019
0,Afghanistan,0.234140,0.164300,0.106180,0.08500,0.00000,0.319820,0.382270,0.401477,0.33200,...,0.302850,0.110370,0.581543,0.53700,0.51700,NotHappy,NotHappy,NotHappy,NotHappy,NotHappy
1,Albania,0.357330,0.318660,0.381499,0.41900,0.38300,0.878670,0.955300,0.996193,0.91600,...,0.804340,0.501630,0.803685,0.81700,0.84800,Happy,Happy,Happy,Happy,Happy
2,Algeria,0.285790,0.210060,0.233336,0.07700,0.08600,0.939290,1.052660,1.091864,0.97900,...,1.077720,0.833090,1.146217,1.15400,1.16000,Happy,Happy,Happy,Happy,Happy
3,Angola,0.103840,0.005890,0.000000,0.00000,0.44974,0.757780,0.847310,0.858428,0.73000,...,0.860400,0.663660,1.104412,1.12500,1.24823,Happy,NotHappy,NotHappy,NotHappy,Happy
4,Angola,0.005890,0.000000,0.000000,0.44974,0.42284,0.847310,0.858428,0.730000,1.05351,...,0.663660,1.104412,1.125000,1.24823,1.06612,NotHappy,NotHappy,NotHappy,Happy,Happy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
765,Zimbabwe,0.258610,0.254290,0.336384,0.40600,0.36100,0.271000,0.350410,0.375847,0.35700,...,1.032760,0.714780,1.083096,1.09400,1.11400,Happy,Happy,NotHappy,NotHappy,NotHappy
766,Zimbabwe,0.254290,0.336384,0.406000,0.36100,0.00000,0.350410,0.375847,0.357000,0.36600,...,0.714780,1.083096,1.094000,1.11400,0.00000,Happy,NotHappy,NotHappy,NotHappy,0
767,Zimbabwe,0.336384,0.406000,0.361000,0.00000,0.00000,0.375847,0.357000,0.366000,0.00000,...,1.083096,1.094000,1.114000,0.00000,0.00000,NotHappy,NotHappy,NotHappy,0,0
768,Zimbabwe,0.406000,0.361000,0.000000,0.00000,0.00000,0.357000,0.366000,0.000000,0.00000,...,1.094000,1.114000,0.000000,0.00000,0.00000,NotHappy,NotHappy,0,0,0
769,Zimbabwe,0.361000,0.000000,0.000000,0.00000,0.00000,0.366000,0.000000,0.000000,0.00000,...,1.114000,0.000000,0.000000,0.00000,0.00000,NotHappy,0,0,0,0

In [5]:
HappinessCSV.drop_duplicates(subset="Country", keep="first", inplace=True)
#HappinessCSV.describe()
Happiness1=HappinessCSV
Happiness1

,Country,Freedom2015,Freedom2016,Freedom2017,Freedom2018,Freedom2019,GDP2015,GDP2016,GDP2017,GDP2018,...,Social_Support2015,Social_Support2016,Social_Support2017,Social_Support2018,Social_Support2019,Happiness2015,Happiness2016,Happiness2017,Happiness2018,Happiness2019
0,Afghanistan,0.23414,0.16430,0.106180,0.085,0.00000,0.31982,0.38227,0.401477,0.332,...,0.30285,0.11037,0.581543,0.537,0.51700,NotHappy,NotHappy,NotHappy,NotHappy,NotHappy
1,Albania,0.35733,0.31866,0.381499,0.419,0.38300,0.87867,0.95530,0.996193,0.916,...,0.80434,0.50163,0.803685,0.817,0.84800,Happy,Happy,Happy,Happy,Happy
2,Algeria,0.28579,0.21006,0.233336,0.077,0.08600,0.93929,1.05266,1.091864,0.979,...,1.07772,0.83309,1.146217,1.154,1.16000,Happy,Happy,Happy,Happy,Happy
3,Angola,0.10384,0.00589,0.000000,0.000,0.44974,0.75778,0.84731,0.858428,0.730,...,0.86040,0.66366,1.104412,1.125,1.24823,Happy,NotHappy,NotHappy,NotHappy,Happy
7,Argentina,0.44974,0.42284,0.494519,0.570,0.47100,1.05351,1.15137,1.185295,1.073,...,1.24823,1.06612,1.440451,1.468,1.43200,Happy,Happy,Happy,Happy,Happy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,Venezuela,0.42908,0.19847,0.153997,0.133,0.15400,1.04424,1.13367,1.128431,0.996,...,1.25596,1.03302,1.431338,1.469,1.42700,Happy,Happy,Happy,Happy,Happy
750,Vietnam,0.59444,0.55954,0.571056,0.618,0.54300,0.63216,0.74037,0.788548,0.715,...,0.91226,0.79117,1.277491,1.365,1.34600,Happy,Happy,Happy,Happy,Happy
755,Yemen,0.35571,0.22870,0.249464,0.244,0.14300,0.54649,0.57939,0.591683,0.442,...,0.68093,0.47493,0.935382,1.073,1.16300,Happy,NotHappy,NotHappy,NotHappy,NotHappy
760,Zambia,0.48827,0.42662,0.461603,0.503,0.43100,0.47038,0.61202,0.636407,0.562,...,0.91612,0.63760,1.003187,1.047,1.05800,Happy,Happy,Happy,Happy,Happy
765,Zimbabwe,0.25861,0.25429,0.336384,0.406,0.36100,0.27100,0.35041,0.375847,0.357,...,1.03276,0.71478,1.083096,1.094,1.11400,Happy,Happy,NotHappy,NotHappy,NotHappy

In [6]:
Happiness1.loc[:,'Happiness2019str'] = Happiness1['Happiness2019']
Happiness1

,Country,Freedom2015,Freedom2016,Freedom2017,Freedom2018,Freedom2019,GDP2015,GDP2016,GDP2017,GDP2018,...,Social_Support2016,Social_Support2017,Social_Support2018,Social_Support2019,Happiness2015,Happiness2016,Happiness2017,Happiness2018,Happiness2019,Happiness2019str
0,Afghanistan,0.23414,0.16430,0.106180,0.085,0.00000,0.31982,0.38227,0.401477,0.332,...,0.11037,0.581543,0.537,0.51700,NotHappy,NotHappy,NotHappy,NotHappy,NotHappy,NotHappy
1,Albania,0.35733,0.31866,0.381499,0.419,0.38300,0.87867,0.95530,0.996193,0.916,...,0.50163,0.803685,0.817,0.84800,Happy,Happy,Happy,Happy,Happy,Happy
2,Algeria,0.28579,0.21006,0.233336,0.077,0.08600,0.93929,1.05266,1.091864,0.979,...,0.83309,1.146217,1.154,1.16000,Happy,Happy,Happy,Happy,Happy,Happy
3,Angola,0.10384,0.00589,0.000000,0.000,0.44974,0.75778,0.84731,0.858428,0.730,...,0.66366,1.104412,1.125,1.24823,Happy,NotHappy,NotHappy,NotHappy,Happy,Happy
7,Argentina,0.44974,0.42284,0.494519,0.570,0.47100,1.05351,1.15137,1.185295,1.073,...,1.06612,1.440451,1.468,1.43200,Happy,Happy,Happy,Happy,Happy,Happy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,Venezuela,0.42908,0.19847,0.153997,0.133,0.15400,1.04424,1.13367,1.128431,0.996,...,1.03302,1.431338,1.469,1.42700,Happy,Happy,Happy,Happy,Happy,Happy
750,Vietnam,0.59444,0.55954,0.571056,0.618,0.54300,0.63216,0.74037,0.788548,0.715,...,0.79117,1.277491,1.365,1.34600,Happy,Happy,Happy,Happy,Happy,Happy
755,Yemen,0.35571,0.22870,0.249464,0.244,0.14300,0.54649,0.57939,0.591683,0.442,...,0.47493,0.935382,1.073,1.16300,Happy,NotHappy,NotHappy,NotHappy,NotHappy,NotHappy
760,Zambia,0.48827,0.42662,0.461603,0.503,0.43100,0.47038,0.61202,0.636407,0.562,...,0.63760,1.003187,1.047,1.05800,Happy,Happy,Happy,Happy,Happy,Happy
765,Zimbabwe,0.25861,0.25429,0.336384,0.406,0.36100,0.27100,0.35041,0.375847,0.357,...,0.71478,1.083096,1.094,1.11400,Happy,Happy,NotHappy,NotHappy,NotHappy,NotHappy

In [7]:
Happiness1['Happiness2020'] = " "
Happiness1

,Country,Freedom2015,Freedom2016,Freedom2017,Freedom2018,Freedom2019,GDP2015,GDP2016,GDP2017,GDP2018,...,Social_Support2017,Social_Support2018,Social_Support2019,Happiness2015,Happiness2016,Happiness2017,Happiness2018,Happiness2019,Happiness2019str,Happiness2020
0,Afghanistan,0.23414,0.16430,0.106180,0.085,0.00000,0.31982,0.38227,0.401477,0.332,...,0.581543,0.537,0.51700,NotHappy,NotHappy,NotHappy,NotHappy,NotHappy,NotHappy,
1,Albania,0.35733,0.31866,0.381499,0.419,0.38300,0.87867,0.95530,0.996193,0.916,...,0.803685,0.817,0.84800,Happy,Happy,Happy,Happy,Happy,Happy,
2,Algeria,0.28579,0.21006,0.233336,0.077,0.08600,0.93929,1.05266,1.091864,0.979,...,1.146217,1.154,1.16000,Happy,Happy,Happy,Happy,Happy,Happy,
3,Angola,0.10384,0.00589,0.000000,0.000,0.44974,0.75778,0.84731,0.858428,0.730,...,1.104412,1.125,1.24823,Happy,NotHappy,NotHappy,NotHappy,Happy,Happy,
7,Argentina,0.44974,0.42284,0.494519,0.570,0.47100,1.05351,1.15137,1.185295,1.073,...,1.440451,1.468,1.43200,Happy,Happy,Happy,Happy,Happy,Happy,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,Venezuela,0.42908,0.19847,0.153997,0.133,0.15400,1.04424,1.13367,1.128431,0.996,...,1.431338,1.469,1.42700,Happy,Happy,Happy,Happy,Happy,Happy,
750,Vietnam,0.59444,0.55954,0.571056,0.618,0.54300,0.63216,0.74037,0.788548,0.715,...,1.277491,1.365,1.34600,Happy,Happy,Happy,Happy,Happy,Happy,
755,Yemen,0.35571,0.22870,0.249464,0.244,0.14300,0.54649,0.57939,0.591683,0.442,...,0.935382,1.073,1.16300,Happy,NotHappy,NotHappy,NotHappy,NotHappy,NotHappy,
760,Zambia,0.48827,0.42662,0.461603,0.503,0.43100,0.47038,0.61202,0.636407,0.562,...,1.003187,1.047,1.05800,Happy,Happy,Happy,Happy,Happy,Happy,
765,Zimbabwe,0.25861,0.25429,0.336384,0.406,0.36100,0.27100,0.35041,0.375847,0.357,...,1.083096,1.094,1.11400,Happy,Happy,NotHappy,NotHappy,NotHappy,NotHappy,

In [8]:
#Happiness.replace(to_replace=r'^ba.$', value='new', regex=True)
#Happiness.replace('Happy','1')
#Happiness=Happiness.replace(to_replace="Happy",value="1")
#Happiness=Happiness.replace(to_replace="NotHappy",value="0")
#Happiness.Happiness2015[Happiness.Happiness2015 == 'Happy'] = 1
#Happiness.Happiness2015[Happiness.Happiness2015 == 'NotHappy'] = 0
#Happiness

In [9]:
Happiness2=Happiness1.replace(to_replace="Happy",value="1")
Happiness=Happiness2.replace(to_replace="NotHappy",value="0")
Happiness

,Country,Freedom2015,Freedom2016,Freedom2017,Freedom2018,Freedom2019,GDP2015,GDP2016,GDP2017,GDP2018,...,Social_Support2017,Social_Support2018,Social_Support2019,Happiness2015,Happiness2016,Happiness2017,Happiness2018,Happiness2019,Happiness2019str,Happiness2020
0,Afghanistan,0.23414,0.16430,0.106180,0.085,0.00000,0.31982,0.38227,0.401477,0.332,...,0.581543,0.537,0.51700,0,0,0,0,0,0,
1,Albania,0.35733,0.31866,0.381499,0.419,0.38300,0.87867,0.95530,0.996193,0.916,...,0.803685,0.817,0.84800,1,1,1,1,1,1,
2,Algeria,0.28579,0.21006,0.233336,0.077,0.08600,0.93929,1.05266,1.091864,0.979,...,1.146217,1.154,1.16000,1,1,1,1,1,1,
3,Angola,0.10384,0.00589,0.000000,0.000,0.44974,0.75778,0.84731,0.858428,0.730,...,1.104412,1.125,1.24823,1,0,0,0,1,1,
7,Argentina,0.44974,0.42284,0.494519,0.570,0.47100,1.05351,1.15137,1.185295,1.073,...,1.440451,1.468,1.43200,1,1,1,1,1,1,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,Venezuela,0.42908,0.19847,0.153997,0.133,0.15400,1.04424,1.13367,1.128431,0.996,...,1.431338,1.469,1.42700,1,1,1,1,1,1,
750,Vietnam,0.59444,0.55954,0.571056,0.618,0.54300,0.63216,0.74037,0.788548,0.715,...,1.277491,1.365,1.34600,1,1,1,1,1,1,
755,Yemen,0.35571,0.22870,0.249464,0.244,0.14300,0.54649,0.57939,0.591683,0.442,...,0.935382,1.073,1.16300,1,0,0,0,0,0,
760,Zambia,0.48827,0.42662,0.461603,0.503,0.43100,0.47038,0.61202,0.636407,0.562,...,1.003187,1.047,1.05800,1,1,1,1,1,1,
765,Zimbabwe,0.25861,0.25429,0.336384,0.406,0.36100,0.27100,0.35041,0.375847,0.357,...,1.083096,1.094,1.11400,1,1,0,0,0,0,

In [10]:
Happiness.Happiness2019str[Happiness.Happiness2019str == '0'] = "NotHappy"
Happiness.Happiness2019str[Happiness.Happiness2019str == '1'] = "Happy" 
Happiness

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Country,Freedom2015,Freedom2016,Freedom2017,Freedom2018,Freedom2019,GDP2015,GDP2016,GDP2017,GDP2018,...,Social_Support2017,Social_Support2018,Social_Support2019,Happiness2015,Happiness2016,Happiness2017,Happiness2018,Happiness2019,Happiness2019str,Happiness2020
0,Afghanistan,0.23414,0.16430,0.106180,0.085,0.00000,0.31982,0.38227,0.401477,0.332,...,0.581543,0.537,0.51700,0,0,0,0,0,NotHappy,
1,Albania,0.35733,0.31866,0.381499,0.419,0.38300,0.87867,0.95530,0.996193,0.916,...,0.803685,0.817,0.84800,1,1,1,1,1,Happy,
2,Algeria,0.28579,0.21006,0.233336,0.077,0.08600,0.93929,1.05266,1.091864,0.979,...,1.146217,1.154,1.16000,1,1,1,1,1,Happy,
3,Angola,0.10384,0.00589,0.000000,0.000,0.44974,0.75778,0.84731,0.858428,0.730,...,1.104412,1.125,1.24823,1,0,0,0,1,Happy,
7,Argentina,0.44974,0.42284,0.494519,0.570,0.47100,1.05351,1.15137,1.185295,1.073,...,1.440451,1.468,1.43200,1,1,1,1,1,Happy,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,Venezuela,0.42908,0.19847,0.153997,0.133,0.15400,1.04424,1.13367,1.128431,0.996,...,1.431338,1.469,1.42700,1,1,1,1,1,Happy,
750,Vietnam,0.59444,0.55954,0.571056,0.618,0.54300,0.63216,0.74037,0.788548,0.715,...,1.277491,1.365,1.34600,1,1,1,1,1,Happy,
755,Yemen,0.35571,0.22870,0.249464,0.244,0.14300,0.54649,0.57939,0.591683,0.442,...,0.935382,1.073,1.16300,1,0,0,0,0,NotHappy,
760,Zambia,0.48827,0.42662,0.461603,0.503,0.43100,0.47038,0.61202,0.636407,0.562,...,1.003187,1.047,1.05800,1,1,1,1,1,Happy,
765,Zimbabwe,0.25861,0.25429,0.336384,0.406,0.36100,0.27100,0.35041,0.375847,0.357,...,1.083096,1.094,1.11400,1,1,0,0,0,NotHappy,

In [11]:
X = Happiness.drop(["Country","Happiness2020", "Happiness2019str"], axis=1)
y = Happiness["Happiness2019str"]
print(X.shape, y.shape)

(170, 40) (170,)

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)

In [14]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [15]:
# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [16]:
# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [17]:
#Create a Deep Learning Model

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
# Create model and add layers
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=40))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [20]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 100)               4100
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 202
=================================================================
Total params: 14,402
Trainable params: 14,402
Non-trainable params: 0
_________________________________________________________________

In [22]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=60,
    shuffle=True,
    verbose=2
)

Train on 127 samples
Epoch 1/60
127/127 - 1s - loss: 0.5692 - accuracy: 0.7717
Epoch 2/60
127/127 - 0s - loss: 0.3208 - accuracy: 0.9055
Epoch 3/60
127/127 - 0s - loss: 0.2136 - accuracy: 0.9055
Epoch 4/60
127/127 - 0s - loss: 0.1859 - accuracy: 0.9055
Epoch 5/60
127/127 - 0s - loss: 0.1775 - accuracy: 0.9055
Epoch 6/60
127/127 - 0s - loss: 0.1698 - accuracy: 0.9055
Epoch 7/60
127/127 - 0s - loss: 0.1557 - accuracy: 0.9055
Epoch 8/60
127/127 - 0s - loss: 0.1368 - accuracy: 0.9055
Epoch 9/60
127/127 - 0s - loss: 0.1164 - accuracy: 0.9370
Epoch 10/60
127/127 - 0s - loss: 0.1052 - accuracy: 0.9764
Epoch 11/60
127/127 - 0s - loss: 0.0901 - accuracy: 0.9843
Epoch 12/60
127/127 - 0s - loss: 0.0750 - accuracy: 0.9843
Epoch 13/60
127/127 - 0s - loss: 0.0646 - accuracy: 0.9843
Epoch 14/60
127/127 - 0s - loss: 0.0530 - accuracy: 0.9921
Epoch 15/60
127/127 - 0s - loss: 0.0438 - accuracy: 0.9921
Epoch 16/60
127/127 - 0s - loss: 0.0361 - accuracy: 0.9921
Epoch 17/60
127/127 - 0s - loss: 0.0307 - accuracy: 0.9921
Epoch 18/60
127/127 - 0s - loss: 0.0251 - accuracy: 0.9921
Epoch 19/60
127/127 - 0s - loss: 0.0202 - accuracy: 1.0000
Epoch 20/60
127/127 - 0s - loss: 0.0166 - accuracy: 1.0000
Epoch 21/60
127/127 - 0s - loss: 0.0141 - accuracy: 1.0000
Epoch 22/60
127/127 - 0s - loss: 0.0115 - accuracy: 1.0000
Epoch 23/60
127/127 - 0s - loss: 0.0097 - accuracy: 1.0000
Epoch 24/60
127/127 - 0s - loss: 0.0081 - accuracy: 1.0000
Epoch 25/60
127/127 - 0s - loss: 0.0069 - accuracy: 1.0000
Epoch 26/60
127/127 - 0s - loss: 0.0059 - accuracy: 1.0000
Epoch 27/60
127/127 - 0s - loss: 0.0053 - accuracy: 1.0000
Epoch 28/60
127/127 - 0s - loss: 0.0046 - accuracy: 1.0000
Epoch 29/60
127/127 - 0s - loss: 0.0041 - accuracy: 1.0000
Epoch 30/60
127/127 - 0s - loss: 0.0036 - accuracy: 1.0000
Epoch 31/60
127/127 - 0s - loss: 0.0033 - accuracy: 1.0000
Epoch 32/60
127/127 - 0s - loss: 0.0029 - accuracy: 1.0000
Epoch 33/60
127/127 - 0s - loss: 0.0027 - accuracy: 1.0000
Epoch 34/60
127/127 - 0s - loss: 0.0024 - accuracy: 1.0000
Epoch 35/60
127/127 - 0s - loss: 0.0022 - accuracy: 1.0000
Epoch 36/60
127/127 - 0s - loss: 0.0021 - accuracy: 1.0000
Epoch 37/60
127/127 - 0s - loss: 0.0019 - accuracy: 1.0000
Epoch 38/60
127/127 - 0s - loss: 0.0018 - accuracy: 1.0000
Epoch 39/60
127/127 - 0s - loss: 0.0017 - accuracy: 1.0000
Epoch 40/60
127/127 - 0s - loss: 0.0015 - accuracy: 1.0000
Epoch 41/60
127/127 - 0s - loss: 0.0014 - accuracy: 1.0000
Epoch 42/60
127/127 - 0s - loss: 0.0013 - accuracy: 1.0000
Epoch 43/60
127/127 - 0s - loss: 0.0013 - accuracy: 1.0000
Epoch 44/60
127/127 - 0s - loss: 0.0012 - accuracy: 1.0000
Epoch 45/60
127/127 - 0s - loss: 0.0011 - accuracy: 1.0000
Epoch 46/60
127/127 - 0s - loss: 0.0010 - accuracy: 1.0000
Epoch 47/60
127/127 - 0s - loss: 9.9250e-04 - accuracy: 1.0000
Epoch 48/60
127/127 - 0s - loss: 9.3566e-04 - accuracy: 1.0000
Epoch 49/60
127/127 - 0s - loss: 8.9587e-04 - accuracy: 1.0000
Epoch 50/60
127/127 - 0s - loss: 8.4553e-04 - accuracy: 1.0000
Epoch 51/60
127/127 - 0s - loss: 7.9992e-04 - accuracy: 1.0000
Epoch 52/60
127/127 - 0s - loss: 7.5784e-04 - accuracy: 1.0000
Epoch 53/60
127/127 - 0s - loss: 7.2889e-04 - accuracy: 1.0000
Epoch 54/60
127/127 - 0s - loss: 6.9842e-04 - accuracy: 1.0000
Epoch 55/60
127/127 - 0s - loss: 6.6988e-04 - accuracy: 1.0000
Epoch 56/60
127/127 - 0s - loss: 6.3273e-04 - accuracy: 1.0000
Epoch 57/60
127/127 - 0s - loss: 6.0139e-04 - accuracy: 1.0000
Epoch 58/60
127/127 - 0s - loss: 5.8316e-04 - accuracy: 1.0000
Epoch 59/60
127/127 - 0s - loss: 5.5810e-04 - accuracy: 1.0000
Epoch 60/60
127/127 - 0s - loss: 5.3414e-04 - accuracy: 1.0000

In [23]:
#Quantify our Trained Model

In [24]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

43/1 - 0s - loss: 0.0047 - accuracy: 1.0000
Normal Neural Network - Loss: 0.009406562807102049, Accuracy: 1.0

In [25]:
encoded_predictions = model.predict_classes(X_test_scaled[:150])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [26]:
print(f"Predicted values: {prediction_labels}")
print(f"Actual Values from 2019: {list(y_test[:150])}")

Predicted values: ['Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'NotHappy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy'
 'Happy' 'NotHappy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'NotHappy' 'Happy'
 'Happy']
Actual Values of 2019: ['Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'NotHappy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'NotHappy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'NotHappy', 'Happy', 'Happy']